# Dataset

In [6]:
text = ""
with open("tinyshakesphere.txt") as f:
    text = f.read()

print(text[:100])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You


In [7]:
vocab = list(set(text))
vocab_size = len(vocab)
print(vocab_size)

65


In [15]:
encode = {val:i for i,val in enumerate(vocab)}
decode = {i:val for i,val in enumerate(vocab)}

print(decode[0])

r


In [35]:
import torch
tokenized_text = torch.tensor([encode[c] for c in text],dtype=torch.long)
print(tokenized_text[:1000])

tensor([30,  7,  0, 33, 39, 45, 58,  7, 39,  7, 62, 42, 14, 37,  8, 27, 42, 63,
        21,  0, 42, 45,  4, 42, 45, 55,  0, 21, 54, 42, 42, 26, 45, 28, 14, 57,
        45, 63, 31,  0, 39, 46, 42,  0, 38, 45, 46, 42, 28,  0, 45, 47, 42, 45,
        33, 55, 42, 28, 16,  5,  8,  8,  1, 53, 53, 37,  8, 13, 55, 42, 28, 16,
        38, 45, 33, 55, 42, 28, 16,  5,  8,  8, 30,  7,  0, 33, 39, 45, 58,  7,
        39,  7, 62, 42, 14, 37,  8, 32, 21, 31, 45, 28,  0, 42, 45, 28, 53, 53,
        45,  0, 42, 33, 21, 53, 19, 42, 26, 45,  0, 28, 39, 46, 42,  0, 45, 39,
        21, 45, 26,  7, 42, 45, 39, 46, 28, 14, 45, 39, 21, 45, 63, 28, 47,  7,
        33, 46, 43,  8,  8,  1, 53, 53, 37,  8, 64, 42, 33, 21, 53, 19, 42, 26,
         5, 45,  0, 42, 33, 21, 53, 19, 42, 26,  5,  8,  8, 30,  7,  0, 33, 39,
        45, 58,  7, 39,  7, 62, 42, 14, 37,  8, 30,  7,  0, 33, 39, 38, 45, 57,
        21, 31, 45, 16, 14, 21,  4, 45, 58, 28,  7, 31, 33, 45, 34, 28,  0, 54,
         7, 31, 33, 45,  7, 33, 45, 54, 

In [36]:
train_data = tokenized_text[:int(0.9*len(text))]
val_data = tokenized_text[int(0.9*len(text)):]

print(len(train_data),len(val_data))

1003854 111540


In [38]:
block_size = 8

def get_batch(split):
    data = train_data if split == 'train' else val_data

    random_starting_indices = torch.randint(len(data) - block_size, (block_size,))

    x = torch.stack([data[i:i+block_size] for i in random_starting_indices])
    y = torch.stack([data[i+1:i+block_size+1] for i in random_starting_indices])
    return x,y
    

x,y = get_batch("train")
print(x)
print(y)


tensor([[45, 28, 45, 55, 28,  0, 28, 26],
        [ 2, 45, 14, 42,  7, 39, 46, 42],
        [42, 45, 57, 21, 31, 38, 45,  7],
        [61, 39,  0, 42, 47, 42, 45, 33],
        [45, 39, 46, 42, 45,  4, 42, 14],
        [28, 57, 45, 47, 57, 45,  0, 42],
        [45, 46,  7, 47, 43,  8,  8, 27],
        [53, 45, 47, 57, 45, 46, 21, 55]])
tensor([[28, 45, 55, 28,  0, 28, 26,  7],
        [45, 14, 42,  7, 39, 46, 42,  0],
        [45, 57, 21, 31, 38, 45,  7, 63],
        [39,  0, 42, 47, 42, 45, 33,  4],
        [39, 46, 42, 45,  4, 42, 14, 54],
        [57, 45, 47, 57, 45,  0, 42, 56],
        [46,  7, 47, 43,  8,  8, 27,  3],
        [45, 47, 57, 45, 46, 21, 55, 42]])
